-- 创建存储过程插入测试数据。
DELIMITER $$
CREATE  PROCEDURE add_test_data(IN n INT)
BEGIN
DECLARE i INT DEFAULT 1;
WHILE i <= n  DO
-- 这里可以自己insert多条
INSERT INTO EXPORT_EXCEL  (NUM,EXPORTTYPE,NAME,CREATETIME ) VALUES (FLOOR(RAND() * 100000),'XLS',FLOOR(RAND() * 100000000) ,NOW());
SET i=i+1;
END WHILE;
END $$
-- 插入一百万测试数据
CALL add_test_data(1000000);

-- 权限RBAC 表设计----------------------------------------------------------------------------------
-- 部门表
CREATE TABLE SYS_DEPT(
ID INT PRIMARY KEY AUTO_INCREMENT COMMENT '部门表主键自增id',
NAME VARCHAR(20) NOT NULL COMMENT '部门名称',
PARENT_ID INT NOT NULL DEFAULT 0 COMMENT '上级部门id',
LEVEL VARCHAR(200) NOT NULL DEFAULT '' COMMENT '部门层级',
SEQ INT NOT NULL DEFAULT 0 COMMENT '部门在当前层级下的顺序',
REMARK VARCHAR(200) COMMENT '备注',
OPERATOR VARCHAR(50) NOT NULL DEFAULT '' COMMENT '操作人',
OPERATOR_TIME DATETIME  DEFAULT NOW() COMMENT '操作时间',
OPERATOR_IP VARCHAR(20) NOT NULL DEFAULT '' COMMENT '操作ip'
) COMMENT '部门表';

-- 用户表
CREATE TABLE SYS_USER(
ID INT PRIMARY KEY AUTO_INCREMENT COMMENT '用户表主键自增id',
USERNAME VARCHAR(20) NOT NULL COMMENT '用户名称',
TELEPHONE VARCHAR(13) NOT NULL DEFAULT 0 COMMENT '手机号',
MAIL VARCHAR(20) NOT NULL DEFAULT '' COMMENT '邮箱',
PASSWORD VARCHAR(40) NOT NULL  COMMENT '密码',
DEPT_ID INT NOT NULL DEFAULT 0 COMMENT '用户所在部门的id',
STATUS INT NOT NULL DEFAULT 1  COMMENT '状态，1：正常，0：冻结状态，2：删除',
REMARK VARCHAR(200) COMMENT '备注',
OPERATOR VARCHAR(20) NOT NULL DEFAULT '' COMMENT '操作人',
OPERATOR_TIME DATETIME  DEFAULT NOW() COMMENT '操作时间',
OPERATOR_IP VARCHAR(20) NOT NULL DEFAULT '' COMMENT '最后一次更新者的ip'
) COMMENT '用户表';

-- 权限模块表
CREATE TABLE SYS_ACL_MODULE(
ID INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT '权限模块主键id',
NAME VARCHAR(20) NOT NULL COMMENT '权限模块名称',
PARENT_ID INT(11) NOT NULL DEFAULT 0 COMMENT '上级权限模块id',
LEVEL VARCHAR(200) NOT NULL DEFAULT '' COMMENT '权限模块层级',
SEQ INT(11) NOT NULL DEFAULT 0 COMMENT '权限模块在当前层级下的顺序',
STATUS INT(11) NOT NULL DEFAULT 1 COMMENT '状态，1：正常，0：冻结',
REMARK VARCHAR(200) DEFAULT '' COMMENT '备注',
OPERATOR VARCHAR(50) NOT NULL DEFAULT '' COMMENT '操作人',
OPERATOR_TIME DATETIME  DEFAULT NOW() COMMENT '操作时间',
OPERATOR_IP VARCHAR(20) NOT NULL DEFAULT '' COMMENT '操作ip'
) COMMENT '权限模块表';

-- 权限表
CREATE TABLE SYS_ACL(
  ID INT(11) PRIMARY KEY AUTO_INCREMENT COMMENT '权限主键id',
  CODE VARCHAR(20) NOT NULL DEFAULT '' COMMENT '权限码',
  NAME VARCHAR(20) NOT NULL DEFAULT '' COMMENT '权限名称',
  ACL_MODULE_ID INT(11) NOT NULL DEFAULT 0 COMMENT '权限所在的权限模块id',
  URL VARCHAR(100) NOT NULL DEFAULT '' COMMENT '请求url',
  TYPE INT(11) NOT NULL DEFAULT 3 COMMENT '1:菜单，2：按钮，3：其他',
  STATUS INT(11) NOT NULL DEFAULT 1 COMMENT '状态，1：正常，0：冻结',
  SEQ INT(11) NOT NULL DEFAULT 0 COMMENT '权限再当前模块下的顺序',
  REMARK VARCHAR(200) DEFAULT '' COMMENT '备注',
  OPERATOR VARCHAR(50) NOT NULL DEFAULT '' COMMENT '操作人',
  OPERATOR_TIME DATETIME  DEFAULT NOW() COMMENT '操作时间',
  OPERATOR_IP VARCHAR(20) NOT NULL DEFAULT '' COMMENT '操作ip'
) COMMENT '权限表';

-- 角色表
CREATE TABLE SYS_ROLE(
ID INT PRIMARY KEY AUTO_INCREMENT COMMENT '角色表主键自增id',
NAME VARCHAR(40) NOT NULL COMMENT '角色名称',
TYPE INT(11) NOT NULL DEFAULT 1 COMMENT '角色类型（1:管理员，2：其他）',
STATUS INT NOT NULL DEFAULT 1  COMMENT '状态，1：可用，0：冻结状态',
REMARK VARCHAR(200) COMMENT '备注',
OPERATOR VARCHAR(20) NOT NULL DEFAULT '' COMMENT '操作人',
OPERATOR_TIME DATETIME  DEFAULT NOW() COMMENT '操作时间',
OPERATOR_IP VARCHAR(20) NOT NULL DEFAULT '' COMMENT '最后一次更新者的ip'
) COMMENT '角色表';

-- 用户角色表
CREATE TABLE SYS_ROLE_USER(
ID INT PRIMARY KEY AUTO_INCREMENT COMMENT '用户角色关联表主键自增id',
ROLE_ID INT(11) NOT NULL COMMENT '角色表id',
USER_ID INT(11) NOT NULL COMMENT '用户表id',
OPERATOR VARCHAR(20) NOT NULL DEFAULT '' COMMENT '操作人',
OPERATOR_TIME DATETIME  DEFAULT NOW() COMMENT '操作时间',
OPERATOR_IP VARCHAR(20) NOT NULL DEFAULT '' COMMENT '最后一次更新者的ip'
) COMMENT '用户角色关联表';

-- 权限角色关联表
CREATE TABLE SYS_ROLE_ACL(
  ID INT PRIMARY KEY AUTO_INCREMENT COMMENT '权限角色关联表主键自增id',
  ROLE_ID INT(11) NOT NULL COMMENT '角色表id',
  ACL_ID INT(11) NOT NULL COMMENT '权限表id',
  OPERATOR VARCHAR(20) NOT NULL DEFAULT '' COMMENT '操作人',
  OPERATOR_TIME DATETIME  DEFAULT NOW() COMMENT '操作时间',
  OPERATOR_IP VARCHAR(20) NOT NULL DEFAULT '' COMMENT '最后一次更新者的ip'
) COMMENT '权限角色关联表';

-- 权限更新记录日志表
CREATE TABLE SYS_LOG(
  ID INT PRIMARY KEY AUTO_INCREMENT COMMENT '用户角色关联表主键自增id',
  TYPE INT(11) NOT NULL DEFAULT 1 COMMENT '权限更新类型（1:部门，2：用户，3：权限模块，4：权限，5：角色，6：角色关系，7：角色权限关系)',
  TARGET_ID INT(11) NOT NULL DEFAULT 1 COMMENT '基于type类型，指定主键id',
  OLD_VALUE text  COMMENT '更新前数据',
  NEW_VALUE text  COMMENT '更新后数据',
  STATUS INT NOT NULL DEFAULT 1  COMMENT '状态，1：可用，0：冻结状态',
  REMARK VARCHAR(200) COMMENT '备注',
  OPERATOR VARCHAR(20) NOT NULL DEFAULT '' COMMENT '操作人',
  OPERATOR_TIME DATETIME  DEFAULT NOW() COMMENT '操作时间',
  OPERATOR_IP VARCHAR(20) NOT NULL DEFAULT '' COMMENT '最后一次更新者的ip'
) COMMENT '权限更新记录日志表';
