-- 部门表
CREATE TABLE SYS_DEPT(
ID INT PRIMARY KEY AUTO_INCREMENT COMMENT '部门表主键自增id',
NAME VARCHAR(20) NOT NULL COMMENT '部门名称',
PARENT_ID INT NOT NULL DEFAULT 0 COMMENT '上级部门id',
LEVEL VARCHAR(200) NOT NULL DEFAULT '' COMMENT '部门层级',
SEQ INT NOT NULL DEFAULT 0 COMMENT '部门在当前层级下的顺序',
REMARK VARCHAR(200) COMMENT '备注',
OPERATOR VARCHAR(50) NOT NULL DEFAULT '' COMMENT '操作人',
OPERATOR_TIME DATETIME  DEFAULT NOW() COMMENT '操作时间',
OPERATOR_IP VARCHAR(20) NOT NULL DEFAULT '' COMMENT '操作ip'
) COMMENT '部门表';


